### ISSUE TITLE
Can't use InfoRepo Discovery on Android

### ISSUE THREAD

**Issue by loveslikey** [objectcomputing/OpenDDS#1594]
Hi:
    I am trying to run opendds on android with DCPSInfoRepo. But I got error,when execute "DevGuideExamples\DCPS\Messenger" example. It seem not process the response data, because of topic not success matched. Here is the log file.
[subscriber.log](https://github.com/objectcomputing/OpenDDS/files/4332440/subscriber.log)
[publisher.log](https://github.com/objectcomputing/OpenDDS/files/4332441/publisher.log)
[DCPSInfoRepo.log](https://github.com/objectcomputing/OpenDDS/files/4332442/DCPSInfoRepo.log)
env:
opendds: 3.14
ACE+TAO:6.5.8
os:window 10 +google emulator
android: Android SDK built for x86_64 ,android version 10,
config:

```
[common]
DCPSInfoRepo=corbaloc::192.168.1.10:12345/DCPSInfoRepo
DCPSGlobalTransportConfig=subscriptiontransport
[config/subscriptiontransport]
transports=tcp

[config/publicationtransport]
transports=tcp

[transport/tcp]
transport_type=tcp
```

### **but it can work at underneath config,**

```
[common]
DCPSGlobalTransportConfig=$file

[domain/42]
DiscoveryConfig=fast_rtps42
DefaultTransportConfig=rtps_config42

[rtps_discovery/fast_rtps42]
ResendPeriod=2
SedpMulticast=0
TTL=20

[config/rtps_config42]
transports=the_rtps_transport42

[transport/the_rtps_transport42]
transport_type=tcp
local_address=10.0.0.14:
use_multicast=0
ttl=20
```

**Comment by ClaytonCalabrese** [comment]
Hello, I have been trying to replicate your process in order to find the problem. 

What emulated device are you using that has an x86_64 architecture?

**Comment by loveslikey** [comment]
Great! I used android studio  comes with the android emulator. In fact,it replicated not just on the simulator, but  also replicated on a real machine of android os( arm64  architecture). I hava tested all kinds of situation about this problem, it can be replicated.

**Comment by iguessthislldo** [comment]
For OpenDDS team members in the future: also see #1325 which was the fix the last time we saw this problem (which was ultimately caused by https://github.com/DOCGroup/ACE_TAO/pull/858) and had the same workaround.

**Comment by iguessthislldo** [comment]
@loveslikey, could you try out the changes in #1626 and confirm those changes work for what you're trying to do?

**Comment by loveslikey** [comment]
I will try it today,Thank you!

**Comment by mitza-oci** [comment]
Fixed in #1626.

**Comment by loveslikey** [comment]
@mitza-oci  Please also accept my apologies for the delay in replying due to personal business. It still cannot work well with "a5515b09b6daec9da1c163c322d1921fccdab3a9" history version. It seems has same log.

**Comment by iguessthislldo** [comment]
We just went with what we had, which needed to be fixed anyway. The fix in #1626 is part of a generic class of cross-shared library symbol visibility problems that we have had on Android before. It's entirely possible you're seeing a separate but similar issue. To see if this is the case, could you completely rebuild OpenDDS with `--macros=no_hidden_visibility=1` added to the configure script options? If I'm right it should work after that. Also regardless of it works or not could you provide the logs again?

**Comment by loveslikey** [comment]
I hava rebuild OpenDDS with --macros=no_hidden_visibility=1 added to the configure script options like `configure --doc-group  --target=android  --macros=ANDROID_ABI=arm64-v8a --host-tools=C:\soft\dds\OpenDDS_Project\build\host --java --force-ace-tao --macros=no_hidden_visibility=1` ,but  it still cannot work well. Here is the log. 
[DCPSInfoRepo.log](https://github.com/objectcomputing/OpenDDS/files/4544597/DCPSInfoRepo.log)
[publisher.log](https://github.com/objectcomputing/OpenDDS/files/4544599/publisher.log)

**Comment by mitza-oci** [comment]
Is the log significantly different from the initial problem you reported?  If so, please open a new issue.  All indications were that this issue was due to symbol visibility, which was fixed (or worked-around using no_hidden_visibility).

**Comment by loveslikey** [comment]
@mitza-oci Sorry,I cannot  understand the logs properly，It  just looks like with  same problem what I encountered   before.I  have  used fixed  version or  added "macros=no_hidden_visibility=1" to the configure script options,but it still cannot work well. If  necessary ,I  will open a new issue.

**Comment by mitza-oci** [comment]
OK, let's not open a new one if we can't determine what the root cause is.
Are you sure that everything was rebuilt with no_hidden_visibility?  You can use the `nm` tool provided in the NDK toolchain to examine shared library symbols.

**Comment by loveslikey** [comment]
Yes,I am sure. I clear all the file and unzip the OpenDSS and ACE+TAO file again. Every  configure command has  added "macros=no_hidden_visibility=1".

**Comment by ClaytonCalabrese** [comment]
From the logs it appears that you may have manually killed the messenger example.  I have to wait about 10-15 seconds for the messenger example to fully associate and begin receiving samples.

**Comment by loveslikey** [comment]
Ok,I got a new log what waiting ablout 50 seconds.
[publisher.log](https://github.com/objectcomputing/OpenDDS/files/4546695/publisher.log)
[DCPSInfoRepo.log](https://github.com/objectcomputing/OpenDDS/files/4546697/DCPSInfoRepo.log)

**Comment by loveslikey** [comment]
@ClaytonCalabrese @mitza-oci 
I hava test many kinds of situation for this problem. Here is the list:
1. "DevGuideExamples\DCPS\Messenge" example  run directly   on  android platform,it works.
2."${DDS_ROOT}\java\tests\messenger" example    run directly  on windows os with java project ,it works.
3,"${DDS_ROOT}\java\tests\messenger" example code  run    on  android platform with android project ,**It cannot work well**（RTPS  also has the same error）.
Is there has any mistake of java code on the android  project?


[MainActivity.txt](https://github.com/objectcomputing/OpenDDS/files/4567469/MainActivity.txt)
`[common]
DCPSInfoRepo=corbaloc::10.0.0.41:12345/DCPSInfoRepo
DCPSGlobalTransportConfig=publicationtransport
[config/subscriptiontransport]
transports=tcp

[config/publicationtransport]
transports=tcp

[transport/tcp]
transport_type=tcp`

**Comment by ClaytonCalabrese** [comment]
The build is functioning properly for me using no_hidden_visilbity=1 and so are the changes in the aforementioned PR, so I think there is some problem happening with your build.

**Comment by loveslikey** [comment]
@ClaytonCalabrese Thank you for your reply. Do you test it on android  app?  I am running  directly on android platform, it works. But run on android platform with android project, It cannot work well. now I using this config instead.
`[common]
DCPSGlobalTransportConfig=$file

[domain/42]
DiscoveryConfig=fast_rtps42
DefaultTransportConfig=rtps_config42

[rtps_discovery/fast_rtps42]
ResendPeriod=2
SedpMulticast=0
TTL=20

[config/rtps_config42]
transports=the_rtps_transport42

[transport/the_rtps_transport42]
transport_type=tcp
local_address=10.0.0.14:
use_multicast=0
ttl=20`

**Comment by mitza-oci** [comment]
@loveslikey since we haven't been able to reproduce this error, I think we'll need some more explanation of what you mean by (and what the distinction is between) "running directly on android platform" and "run on android platform with android project".
